/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedFeedbackRouteImport } from './routes/_authenticated/feedback'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as AuthenticatedSystemHealthRouteImport } from './routes/_authenticated/system-health'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth.update-password'
import { Route as LegalAcceptableUseRouteImport } from './routes/legal.acceptable-use'
import { Route as LegalChildSafetyRouteImport } from './routes/legal.child-safety'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as AuthenticatedAccountSuspendedRouteImport } from './routes/_authenticated/account.suspended'
import { Route as AuthenticatedAssistantIndexRouteImport } from './routes/_authenticated/assistant.index'
import { Route as AuthenticatedAssistantThreadIdRouteImport } from './routes/_authenticated/assistant.$threadId'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages.index'
import { Route as AuthenticatedMessagesConversationIdRouteImport } from './routes/_authenticated/messages.$conversationId'
import { Route as AuthenticatedOnboardingComplianceRouteImport } from './routes/_authenticated/onboarding.compliance'
import { Route as AuthenticatedOnboardingLanguageRouteImport } from './routes/_authenticated/onboarding.language'
import { Route as AuthenticatedOnboardingModelRouteImport } from './routes/_authenticated/onboarding.model'
import { Route as AuthenticatedOnboardingSystemAdmissionRouteImport } from './routes/_authenticated/onboarding.system-admission'
import { Route as AuthenticatedSchoolIndexRouteImport } from './routes/_authenticated/school.index'
import { Route as AuthenticatedSchoolSubjectRouteImport } from './routes/_authenticated/school.$subject'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFeedbackRoute = AuthenticatedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSystemHealthRoute =
  AuthenticatedSystemHealthRouteImport.update({
    id: '/system-health',
    path: '/system-health',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => AuthRoute,
} as any)
const LegalAcceptableUseRoute = LegalAcceptableUseRouteImport.update({
  id: '/legal/acceptable-use',
  path: '/legal/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalChildSafetyRoute = LegalChildSafetyRouteImport.update({
  id: '/legal/child-safety',
  path: '/legal/child-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountSuspendedRoute =
  AuthenticatedAccountSuspendedRouteImport.update({
    id: '/account/suspended',
    path: '/account/suspended',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssistantIndexRoute =
  AuthenticatedAssistantIndexRouteImport.update({
    id: '/assistant/',
    path: '/assistant/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssistantThreadIdRoute =
  AuthenticatedAssistantThreadIdRouteImport.update({
    id: '/assistant/$threadId',
    path: '/assistant/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesConversationIdRoute =
  AuthenticatedMessagesConversationIdRouteImport.update({
    id: '/messages/$conversationId',
    path: '/messages/$conversationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingComplianceRoute =
  AuthenticatedOnboardingComplianceRouteImport.update({
    id: '/onboarding/compliance',
    path: '/onboarding/compliance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingLanguageRoute =
  AuthenticatedOnboardingLanguageRouteImport.update({
    id: '/onboarding/language',
    path: '/onboarding/language',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingModelRoute =
  AuthenticatedOnboardingModelRouteImport.update({
    id: '/onboarding/model',
    path: '/onboarding/model',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingSystemAdmissionRoute =
  AuthenticatedOnboardingSystemAdmissionRouteImport.update({
    id: '/onboarding/system-admission',
    path: '/onboarding/system-admission',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchoolIndexRoute =
  AuthenticatedSchoolIndexRouteImport.update({
    id: '/school/',
    path: '/school/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchoolSubjectRoute =
  AuthenticatedSchoolSubjectRouteImport.update({
    id: '/school/$subject',
    path: '/school/$subject',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/help': typeof AuthenticatedHelpRoute
  '/home': typeof AuthenticatedHomeRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/system-health': typeof AuthenticatedSystemHealthRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/child-safety': typeof LegalChildSafetyRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/account/suspended': typeof AuthenticatedAccountSuspendedRoute
  '/assistant/$threadId': typeof AuthenticatedAssistantThreadIdRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/onboarding/compliance': typeof AuthenticatedOnboardingComplianceRoute
  '/onboarding/language': typeof AuthenticatedOnboardingLanguageRoute
  '/onboarding/model': typeof AuthenticatedOnboardingModelRoute
  '/onboarding/system-admission': typeof AuthenticatedOnboardingSystemAdmissionRoute
  '/school/$subject': typeof AuthenticatedSchoolSubjectRoute
  '/assistant/': typeof AuthenticatedAssistantIndexRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/school/': typeof AuthenticatedSchoolIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/help': typeof AuthenticatedHelpRoute
  '/home': typeof AuthenticatedHomeRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/system-health': typeof AuthenticatedSystemHealthRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/child-safety': typeof LegalChildSafetyRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/account/suspended': typeof AuthenticatedAccountSuspendedRoute
  '/assistant/$threadId': typeof AuthenticatedAssistantThreadIdRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/onboarding/compliance': typeof AuthenticatedOnboardingComplianceRoute
  '/onboarding/language': typeof AuthenticatedOnboardingLanguageRoute
  '/onboarding/model': typeof AuthenticatedOnboardingModelRoute
  '/onboarding/system-admission': typeof AuthenticatedOnboardingSystemAdmissionRoute
  '/school/$subject': typeof AuthenticatedSchoolSubjectRoute
  '/assistant': typeof AuthenticatedAssistantIndexRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/school': typeof AuthenticatedSchoolIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/feedback': typeof AuthenticatedFeedbackRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/_authenticated/system-health': typeof AuthenticatedSystemHealthRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/child-safety': typeof LegalChildSafetyRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/_authenticated/account/suspended': typeof AuthenticatedAccountSuspendedRoute
  '/_authenticated/assistant/$threadId': typeof AuthenticatedAssistantThreadIdRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/_authenticated/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/_authenticated/onboarding/compliance': typeof AuthenticatedOnboardingComplianceRoute
  '/_authenticated/onboarding/language': typeof AuthenticatedOnboardingLanguageRoute
  '/_authenticated/onboarding/model': typeof AuthenticatedOnboardingModelRoute
  '/_authenticated/onboarding/system-admission': typeof AuthenticatedOnboardingSystemAdmissionRoute
  '/_authenticated/school/$subject': typeof AuthenticatedSchoolSubjectRoute
  '/_authenticated/assistant/': typeof AuthenticatedAssistantIndexRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/school/': typeof AuthenticatedSchoolIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/feedback'
    | '/help'
    | '/home'
    | '/planner'
    | '/profile'
    | '/settings'
    | '/stats'
    | '/system-health'
    | '/api/chat'
    | '/auth/update-password'
    | '/legal/acceptable-use'
    | '/legal/child-safety'
    | '/legal/privacy'
    | '/legal/terms'
    | '/account/suspended'
    | '/assistant/$threadId'
    | '/chat/$threadId'
    | '/messages/$conversationId'
    | '/onboarding/compliance'
    | '/onboarding/language'
    | '/onboarding/model'
    | '/onboarding/system-admission'
    | '/school/$subject'
    | '/assistant/'
    | '/chat/'
    | '/messages/'
    | '/school/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/feedback'
    | '/help'
    | '/home'
    | '/planner'
    | '/profile'
    | '/settings'
    | '/stats'
    | '/system-health'
    | '/api/chat'
    | '/auth/update-password'
    | '/legal/acceptable-use'
    | '/legal/child-safety'
    | '/legal/privacy'
    | '/legal/terms'
    | '/account/suspended'
    | '/assistant/$threadId'
    | '/chat/$threadId'
    | '/messages/$conversationId'
    | '/onboarding/compliance'
    | '/onboarding/language'
    | '/onboarding/model'
    | '/onboarding/system-admission'
    | '/school/$subject'
    | '/assistant'
    | '/chat'
    | '/messages'
    | '/school'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/feedback'
    | '/_authenticated/help'
    | '/_authenticated/home'
    | '/_authenticated/planner'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/stats'
    | '/_authenticated/system-health'
    | '/api/chat'
    | '/auth/update-password'
    | '/legal/acceptable-use'
    | '/legal/child-safety'
    | '/legal/privacy'
    | '/legal/terms'
    | '/_authenticated/account/suspended'
    | '/_authenticated/assistant/$threadId'
    | '/_authenticated/chat/$threadId'
    | '/_authenticated/messages/$conversationId'
    | '/_authenticated/onboarding/compliance'
    | '/_authenticated/onboarding/language'
    | '/_authenticated/onboarding/model'
    | '/_authenticated/onboarding/system-admission'
    | '/_authenticated/school/$subject'
    | '/_authenticated/assistant/'
    | '/_authenticated/chat/'
    | '/_authenticated/messages/'
    | '/_authenticated/school/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  LegalAcceptableUseRoute: typeof LegalAcceptableUseRoute
  LegalChildSafetyRoute: typeof LegalChildSafetyRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/feedback': {
      id: '/_authenticated/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system-health': {
      id: '/_authenticated/system-health'
      path: '/system-health'
      fullPath: '/system-health'
      preLoaderRoute: typeof AuthenticatedSystemHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/legal/acceptable-use': {
      id: '/legal/acceptable-use'
      path: '/legal/acceptable-use'
      fullPath: '/legal/acceptable-use'
      preLoaderRoute: typeof LegalAcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/child-safety': {
      id: '/legal/child-safety'
      path: '/legal/child-safety'
      fullPath: '/legal/child-safety'
      preLoaderRoute: typeof LegalChildSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/suspended': {
      id: '/_authenticated/account/suspended'
      path: '/account/suspended'
      fullPath: '/account/suspended'
      preLoaderRoute: typeof AuthenticatedAccountSuspendedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant/': {
      id: '/_authenticated/assistant/'
      path: '/assistant'
      fullPath: '/assistant/'
      preLoaderRoute: typeof AuthenticatedAssistantIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant/$threadId': {
      id: '/_authenticated/assistant/$threadId'
      path: '/assistant/$threadId'
      fullPath: '/assistant/$threadId'
      preLoaderRoute: typeof AuthenticatedAssistantThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/$conversationId': {
      id: '/_authenticated/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof AuthenticatedMessagesConversationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/compliance': {
      id: '/_authenticated/onboarding/compliance'
      path: '/onboarding/compliance'
      fullPath: '/onboarding/compliance'
      preLoaderRoute: typeof AuthenticatedOnboardingComplianceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/language': {
      id: '/_authenticated/onboarding/language'
      path: '/onboarding/language'
      fullPath: '/onboarding/language'
      preLoaderRoute: typeof AuthenticatedOnboardingLanguageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/model': {
      id: '/_authenticated/onboarding/model'
      path: '/onboarding/model'
      fullPath: '/onboarding/model'
      preLoaderRoute: typeof AuthenticatedOnboardingModelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/system-admission': {
      id: '/_authenticated/onboarding/system-admission'
      path: '/onboarding/system-admission'
      fullPath: '/onboarding/system-admission'
      preLoaderRoute: typeof AuthenticatedOnboardingSystemAdmissionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/school/': {
      id: '/_authenticated/school/'
      path: '/school'
      fullPath: '/school/'
      preLoaderRoute: typeof AuthenticatedSchoolIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/school/$subject': {
      id: '/_authenticated/school/$subject'
      path: '/school/$subject'
      fullPath: '/school/$subject'
      preLoaderRoute: typeof AuthenticatedSchoolSubjectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFeedbackRoute: typeof AuthenticatedFeedbackRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedSystemHealthRoute: typeof AuthenticatedSystemHealthRoute
  AuthenticatedAccountSuspendedRoute: typeof AuthenticatedAccountSuspendedRoute
  AuthenticatedAssistantThreadIdRoute: typeof AuthenticatedAssistantThreadIdRoute
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedMessagesConversationIdRoute: typeof AuthenticatedMessagesConversationIdRoute
  AuthenticatedOnboardingComplianceRoute: typeof AuthenticatedOnboardingComplianceRoute
  AuthenticatedOnboardingLanguageRoute: typeof AuthenticatedOnboardingLanguageRoute
  AuthenticatedOnboardingModelRoute: typeof AuthenticatedOnboardingModelRoute
  AuthenticatedOnboardingSystemAdmissionRoute: typeof AuthenticatedOnboardingSystemAdmissionRoute
  AuthenticatedSchoolSubjectRoute: typeof AuthenticatedSchoolSubjectRoute
  AuthenticatedAssistantIndexRoute: typeof AuthenticatedAssistantIndexRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
  AuthenticatedSchoolIndexRoute: typeof AuthenticatedSchoolIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFeedbackRoute: AuthenticatedFeedbackRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedSystemHealthRoute: AuthenticatedSystemHealthRoute,
  AuthenticatedAccountSuspendedRoute: AuthenticatedAccountSuspendedRoute,
  AuthenticatedAssistantThreadIdRoute: AuthenticatedAssistantThreadIdRoute,
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedMessagesConversationIdRoute:
    AuthenticatedMessagesConversationIdRoute,
  AuthenticatedOnboardingComplianceRoute:
    AuthenticatedOnboardingComplianceRoute,
  AuthenticatedOnboardingLanguageRoute: AuthenticatedOnboardingLanguageRoute,
  AuthenticatedOnboardingModelRoute: AuthenticatedOnboardingModelRoute,
  AuthenticatedOnboardingSystemAdmissionRoute:
    AuthenticatedOnboardingSystemAdmissionRoute,
  AuthenticatedSchoolSubjectRoute: AuthenticatedSchoolSubjectRoute,
  AuthenticatedAssistantIndexRoute: AuthenticatedAssistantIndexRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
  AuthenticatedSchoolIndexRoute: AuthenticatedSchoolIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  LegalAcceptableUseRoute: LegalAcceptableUseRoute,
  LegalChildSafetyRoute: LegalChildSafetyRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
